<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Popocatepetl.Application\Popocatepetl.Application.csproj" />
    <ProjectReference Include="..\Popocatepetl.Infrastructure\Popocatepetl.Infrastructure.csproj" />
  </ItemGroup>

</Project>
